### ISSUE TITLE
alternative guide using binance/connector-python

### ISSUE THREAD

**Issue by abstractumx** [PythonForForex/Binance-api-step-by-step-guide#14]
Hello, 

have you ever thought to do an alternative guide using official Binance python API?

I've found this repo:
https://github.com/binance/binance-connector-python

Thanks

**Comment by PythonForForex** [comment]
Hello, 

The repo you have linked was mentioned in the guide as an option. Python-binance has been around a bit longer and is more popular which is why it was used in the guide.

At the time of writing, I had thought the binance connector library was a bit convoluted but it seems to look a lot cleaner/simpler now. Perhaps not all that much different from Python-binance aside from the websocket implementation.

**Comment by abstractumx** [comment]
We could make a new fresh API if you are interested.

Thanks
A

Il giorno sab 7 mag 2022 alle ore 16:40 Jignesh Davda <
***@***.***> ha scritto:
